name: Performance Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'tests/performance/**'
      - '.github/workflows/performance-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tests/performance/**'
      - '.github/workflows/performance-tests.yml'
  workflow_dispatch:

jobs:
  performance:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-focal
      options: --shm-size=2gb

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Artillery
        run: npm install -g artillery@latest
      
      - name: Run performance tests
        run: |
          mkdir -p reports/performance
          artillery run --output reports/performance/report.json tests/performance/scenarios/load-test.yml
          artillery report reports/performance/report.json -o reports/performance/report.html
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'http://localhost:3000' }}
          
      - name: Upload performance report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: reports/performance/
          retention-days: 30
