name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: ci
      CI: true
      PORTAL_USERNAME: ${{ secrets.PORTAL_USERNAME }}
      PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
      COD_USER: ${{ secrets.COD_USER }}
      COD_USER_EUR_BVB: ${{ secrets.COD_USER_EUR_BVB }}
      COD_USER_EUR_INTL: ${{ secrets.COD_USER_EUR_INTL }}
      COD_USER_CAD: ${{ secrets.COD_USER_CAD }}
      COD_USER_GBP: ${{ secrets.COD_USER_GBP }}
      COD_USER_PLN: ${{ secrets.COD_USER_PLN }}
      COD_USER_USD: ${{ secrets.COD_USER_USD }}
      PORTAL_URL: ${{ secrets.PORTAL_URL }}
      PAGE_TITLE: ${{ secrets.PAGE_TITLE }}
      URL_LOGIN: ${{ secrets.URL_LOGIN }}
      APLIC_URL: ${{ secrets.APLIC_URL }}
      PORTAL_SUBCONT: ${{ secrets.PORTAL_SUBCONT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests with JUnit report
        run: npx playwright test --reporter=junit --output=test-results

      - name: Prepare reports folder
        run: mkdir -p reports

      - name: Run Cucumber tests with JUnit report
        run: npx cucumber-js --format junit:reports/cucumber-results.xml

      - name: Upload Playwright test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-junit
          path: test-results/*.xml

      - name: Upload Cucumber test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-junit
          path: reports/cucumber-results.xml

      - name: Report Playwright test results to GitHub Checks
        uses: dorny/test-reporter@v1
        with:
          name: Playwright Tests
          path: test-results/*.xml
          reporter: junit

      - name: Report Cucumber test results to GitHub Checks
        uses: dorny/test-reporter@v1
        with:
          name: Cucumber Tests
          path: reports/cucumber-results.xml
          reporter: junit
